Updated bspwm_scratchpad

diff --git a/.local/bin/bspwm_scratchpad b/.local/bin/bspwm_scratchpad
--- a/.local/bin/bspwm_scratchpad
+++ b/.local/bin/bspwm_scratchpad
@@ -1,30 +1,49 @@
 #!/usr/bin/env bash
 
-# Example sxhkdrc
-# super + m
-# 	bspwm_scratchpad "math" "${TERMINAL} --class math --title math --command python3"
+# Example sxhkdrc:
+#   super + n
+#   	bspwm_scratchpad "scratchpad" "alacritty --class scratchpad --title scratchpad --option font.size=14 --command tmux new-session -A -s scratchpad" "1600x1000+0+0"
+#   super + m
+#   	bspwm_scratchpad "math" "alacritty --class math --title math --option font.size=18 --command tmux new-session -A -s math xonsh" "1200x800+0+0"
+#   super + p
+#   	bspwm_scratchpad "spotify" "spotify" "1000x1600+0+0"
+# $1 and $2 are required, see below for usage.
 
+# The window class, get this with `xprop`
 class="${1:-scratchpad}"
+# The command used to run the program
 terminal_command="${2:-${TERMINAL} --class ${class} --title scratchpad}"
+# The size of the window
 size="${3:-1600x1000+0+0}"
+# Should the window stay on the focused workspace?
 sticky="${4:-on}"
+# The window state, see `man bspc`
 state="${5:-floating}"
+# Should the window automatically be centered?
 center="${6:-true}"
+# TODO
+# allow_reposition="${4:-true}"
 
-#dependencies=("xdo" "xprop" "awk")
-#for cmd in "${dependencies[@]}"; do
-#  if ! command -v "${cmd}" >/dev/null 2>&1; then
-#    printf "Command ${cmd} not found.\n"
-#    notify-send "Scratchpad" "Command ${cmd} not found."
-#    missingDependencies='true'
-#  fi
-#done
-#test -n "${missingDependencies}" && exit 1
+check_deps () { # <dependencies:@string> -> Void {{{
+  _deps=${@}
+  _missing=""
+  for _dep in ${_deps}; do
+    if ! hash "${_dep}" 2>/dev/null; then
+      _missing="${_missing} ${_dep}"
+    fi
+  done
+  if test -n "${_missing}"; then
+    printf "Missing required dependencies:${_missing}\n"
+    notify-send "bspwm scratchpad" "Missing required dependencies:${_missing}"
+    exit 1
+  fi
+} # }}}
+check_deps xdo xprop awk bspc
 
 id="$(xdo id -n ${class} | head -1)"
 if test -z "${id}"; then
   bspc rule -r "*:${class}"
-  bspc rule -a "*:${class}" sticky=on state=floating center=true rectangle="${size}"
+  bspc rule -a "*:${class}" sticky="${sticky}" state="${state}" center="${center}" rectangle="${size}"
   eval "${terminal_command}" &
   # Sleep until window has started
   until test ! -z $(xdo id -n ${class} | head -1); do
