dirtygit

diff --git a/.local/bin/dirtygit b/.local/bin/dirtygit
--- a/.local/bin/dirtygit
+++ b/.local/bin/dirtygit
@@ -1,26 +1,51 @@
 #!/usr/bin/env bash
-set -o errexit   # abort on nonzero exitstatus
+# vim: set foldmethod=marker nomodeline:
+# Options {{{
+set -o errexit   # abort on nonzero exit status
 set -o nounset   # abort on unbound variable
 set -o pipefail  # don't hide errors within pipes
+set -o noclobber # disallow redirect overwriting
+# }}}
 
-GIT_ADD="${GIT_ADD:-.}"
-GIT_DIR="${GIT_DIR:-./.git}"
-WORK_TREE="${WORK_TREE:-.}"
+# Magic variables {{{
+__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)" # /path/to/dir
+__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"                     # /path/to/dir/file
+__base="$(basename ${__file})"                                        # file
+# }}}
 
-cleanup () {
+# Colours {{{
+reset=$'\e[0;39m'
+#red='\e[31m'
+#green='\e[32m'
+#blue='\e[94m'
+#yellow='\e[33m'
+
+gray=$'\e[90m'
+red=$'\e[91m'
+green=$'\e[92m'
+yellow=$'\e[93m'
+blue=$'\e[94m'
+magenta=$'\e[95m'
+cyan=$'\e[96m'
+
+bGray=$'\e[100m'
+bRed=$'\e[101m'
+bGreen=$'\e[102m'
+bYellow=$'\e[103m'
+bBlue=$'\e[104m'
+bMagenta=$'\e[105m'
+bCyan=$'\e[106m'
+# }}}
+
+cleanup () { # {{{
   tput cnorm
   printf "${reset}"
   exit 1
 }
 trap cleanup INT
+# }}}
 
-reset='\e[0;39m'
-blue='\e[94m'
-green='\e[32m'
-yellow='\e[33m'
-red='\e[31m'
-
-waiting_dots () {
+waiting_dots () { # {{{
   local d='0.35'
   local i='.'
   tput civis
@@ -36,26 +61,95 @@ waiting_dots () {
   printf "\r"
   sleep "${d}"
   tput cnorm
-}
+} # }}}
 
-printf "\n${blue}| ADDING \e[0;39m\n\n"
-printf "\$ ${yellow}git --git-dir=${GIT_DIR} --work-tree=${WORK_TREE} ${red}add ${GIT_ADD}${reset}\n"
-waiting_dots
-git --git-dir="${GIT_DIR}" --work-tree="${WORK_TREE}" add "${GIT_ADD}"
+helpme () { # {{{
+	cat <<-EOMAN
+	${green}Usage:${reset} ${blue}dirtygit${reset} ${gray}[${red}options${gray}] [${red}command${gray}]${reset}
 
-printf "\n${blue}| COMMITTING \e[0;39m'${*}'\n\n"
-printf "\$ ${yellow}git --git-dir=${GIT_DIR} --work-tree=${WORK_TREE} ${red}commit -m ${*}${reset}\n"
-waiting_dots
-git --git-dir="${GIT_DIR}" --work-tree="${WORK_TREE}" commit -m "${*}"
+	${green}Options:${reset}
+	  -h${gray},${reset} --help          Display this message.
+	  -y${gray},${reset} --yes           Don't prompt for confirmation.
+	  --git-dir    ${gray}<${red}dir${gray}>${reset}  Git-repo-files directory, see: \`man git\`.
+	  --work-tree  ${gray}<${red}dir${gray}>${reset}  Git work tree, see: \`man git\`.
+	  --git-add    ${gray}<${red}str${gray}>${reset}  What to send to \`git add\`, default: '.'.
 
-printf "\n${blue}| PULLING \e[0;39m\n\n"
-printf "\$ ${yellow}git --git-dir=${GIT_DIR} --work-tree=${WORK_TREE} ${red}pull${reset}\n"
-waiting_dots
-git --git-dir="${GIT_DIR}" --work-tree="${WORK_TREE}" pull
+	${green}Commands:${reset}
+	  Commit message      Commit message used with git, default: \`date +'%a-%Y-%m-%dT%T%z'\`.
 
-printf "\n${blue}| PUSHING \e[0;39m\n\n"
-printf "\$ ${yellow}git --git-dir=${GIT_DIR} --work-tree=${WORK_TREE} ${red}push${reset}\n"
-waiting_dots
-git --git-dir="${GIT_DIR}" --work-tree="${WORK_TREE}" push
+	${green}Examples:${yellow}
+	  dirtygit
+	  dirtygit -y
+	  dirtygit Initial commit
+	  dirtygit --git-dir "\${HOME}/dotfiles" --work-tree "\${HOME}" --git-add '-u'
+	${reset}
+	EOMAN
+} # }}}
 
-printf "\n${green}| DONE! \e[0;39m\n\n"
+confirm () { # {{{
+  msg="${1:-Continue?}"
+  printf "${msg} [Y/n]"
+  read -p " " -n 1 -r </dev/tty
+  printf "\n"
+  if [[ "${REPLY}" =~ ^[Nn]$ ]]; then
+    exit 1
+  fi
+} # }}}
+
+commit () { # {{{
+  printf "\n${blue}| ADDING ${reset}\n\n"
+  printf "\$ ${yellow}${gitCommand[*]} ${red}add ${gitAdd}${reset}\n"
+  test -n "${yes}" && waiting_dots || confirm
+  eval "echo ${gitCommand[*]} add ${gitAdd}"
+
+  printf "\n${blue}| COMMITTING ${reset}'${*}'\n\n"
+  printf "\$ ${yellow}${gitCommand[*]} ${red}commit -m "${*}"${reset}\n"
+  test -n "${yes}" && waiting_dots || confirm
+  eval "echo ${gitCommand[*]} commit -m '${*}'"
+
+  printf "\n${blue}| PULLING ${reset}\n\n"
+  printf "\$ ${yellow}${gitCommand[*]} ${red}pull${reset}\n"
+  test -n "${yes}" && waiting_dots || confirm
+  eval "echo ${gitCommand[*]} pull"
+
+  printf "\n${blue}| PUSHING ${reset}\n\n"
+  printf "\$ ${yellow}${gitCommand[*]} ${red}push${reset}\n"
+  test -n "${yes}" && waiting_dots || confirm
+  eval "echo ${gitCommand[*]} push"
+
+  printf "\n${green}| DONE! ${reset}\n\n"
+} # }}}
+
+# Arguments {{{
+yes='' gitAdd='.'
+positional=()
+gitCommand=("git")
+while test "${#}" -gt "0"; do
+  case "${1}" in
+    -h|--help)
+      helpme
+      exit 0
+      shift;;
+    --git-dir|--work-tree)
+      gitCommand+=("${1}=${2}")
+      shift;shift;;
+    --git-add)
+      gitAdd="${2}"
+      shift;shift;;
+    -y|--yes)
+      yes='true'
+      shift;;
+    *)
+      positional+=("${1}")
+      shift;;
+  esac
+done
+
+set -- "${positional[@]}"
+
+if test "${#}" -lt "1"; then
+  set -- "$(date +'%a-%Y-%m-%dT%T%z')"
+fi
+
+commit "${@}"
+# }}}
